
//variable to track the pattern generated by the computer
var gamePattern=[];
//variable used to track the pattern clicked by the user
var userClickedPattern=[];

var buttonColor=["red","blue","green","yellow"]
//current level that the player is playing
var levelCount=0;

var started=false;

//event handler function used to handle the jeydown event
$(document).keydown(function(){
  //this method changes the text to level 0 and calls the nextSequence() method to start the game
  if(!started)
  {
    $("#level-title").text("level 0")
    nextSequence();
    started=true;
  }
})

//function used to generate a random color
function nextSequence(){

  /*at first,a randomNumber is generated and then we push the color corresponding to the randomNumber in the gamePattern so that
  so that we can keep track of the computer generated colors,finally levelcount is increased*/
  userClickedPattern=[];

  var randomNumber=Math.floor(Math.random() * 4);
  var randomChosenColor=buttonColor[randomNumber];
  gamePattern.push(randomChosenColor);
  levelCount++;
  //button animations
  $("#"+randomChosenColor).fadeOut(90).fadeIn(90);
  playSound(randomChosenColor);

  //updating level
  $("#level-title").text("level "+levelCount);
}

//event handler function when the button is clicked
$(".btn").click( function() {

  //first,it would get the color chosen by the user,then add it to the userClickedPattern
  var userChosenColor=$(this).attr("id");
  userClickedPattern.push(userChosenColor);

  //call for the method to check the correctness of the pattern clicked by the user.
  checkAnswer(userClickedPattern.length);

  //button animation
  playSound(userChosenColor);
  animatePress(userChosenColor);
}
);

function checkAnswer(currentLevel)
{
  if(userClickedPattern[currentLevel-1]===gamePattern[currentLevel-1]){
    if(userClickedPattern.length===gamePattern.length){
        setTimeout(function(){nextSequence()},1000);
    }
  }else{
    var wrong=new Audio("sounds/wrong.mp3");
    wrong.play();
    $("body").addClass("game-over");
    setTimeout(function(){$("body").removeClass("game-over")},200);
    $("#level-title").text("Game Over,press any key to restart");
    startOver();
  }
}

//method to start the game again after gameover
function startOver()
{
  levelCount=0;
  gamePattern=[];
  started=false;
}

//button animation methods.
function animatePress(currentColor){
  $("#"+currentColor).addClass("pressed");
  setTimeout(function(){$("#"+currentColor).removeClass("pressed");},100)
}

//method to play sound when the button is clicked.
function playSound(color){
  var sound=new Audio("sounds/"+color+".mp3");
  sound.play();
}
